name: forecast_app
description: A minimal Flutter counter application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # Navigation
  go_router: ^14.6.2
  
  # Networking
  dio: ^5.7.0
  html: ^0.15.4
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Utils
  intl: ^0.19.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true